---

- name: add new configuration to "postgresql.conf"
  blockinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    block: |
      include 'server.conf'

- name: add new configuration to "server.conf"
  blockinfile:
    create: yes
    owner: postgres
    group: postgres
    dest: /var/lib/pgsql/data/server.conf
    block: |
      listen_addresses = '*'
      wal_level = 'hot_standby'
      archive_mode = on
      archive_command = 'true'
      max_wal_senders = 6
      hot_standby = on
  notify: "Restart PostgreSQL Service"

- name: add new configuration to "pg_hba.conf"
  blockinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0                md5
      host    replication     replicant       0.0.0.0/0                md5
  notify: "Restart PostgreSQL Service"

- name: update environment variables in UNIX account postgres
  blockinfile:
    create: yes
    owner: postgres
    group: postgres
    dest: /var/lib/pgsql/.pgsql_profile
    block: |
      export PGHOST=/tmp PAGER=less PGDATA=/var/lib/pgsql/data
  notify: "Restart PostgreSQL Service"

- meta: flush_handlers

- name: wait until postgresql userdata exists before continuing
  wait_for:
    path: /var/lib/pgsql/data/postmaster.pid

- name: set postgres user password
  become: true
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "{{ postgresql_admin_password }}"
    encrypted: yes

- name: create ROLE replicant
  become: true
  become_user: postgres
  postgresql_user:
    db: postgres
    name: replicant
    password: "{{ postgresql_replicant_password }}"
    role_attr_flags: LOGIN,REPLICATION
