---

- service:
    name: postgresql
    state: stopped

- file:
   path: /var/lib/pgsql/data/
   state: absent

- file:
   path:  /var/lib/pgsql/data/
   owner: postgres
   group: postgres
   mode:  0700
   state: directory

- name: execute base backup
  shell: export PGPASSWORD="{{ passwd }}" && /usr/bin/pg_basebackup -h pg1 -U replicant -D /var/lib/pgsql/data -P -v --xlog-method=stream 2>&1

- name: add new configuration "recovery.conf"
  blockinfile:
    create: yes
    dest: /var/lib/pgsql/data/recovery.conf
    block: |
      standby_mode = 'on'
      primary_conninfo = 'user=replicant password={{ passwd }} host={{ master }} port=5432 sslmode=prefer'
      recovery_target_timeline = 'latest'

- service:
    name: postgresql
    state: started

