---

- name: Install Containerized PostgreSQL
  include_tasks: install_containerized.yml
  when:
    - mode == "containerized"

- name: Flush Handlers (Postgresql)
  meta: flush_handlers

- name: Install Non-Containerized PostgreSQL
  include_tasks: install_non_containerized.yml
  when:
    - postgresql_ha_mode == True
    - mode == "non-containerized"
    - '"db-hosts" in group_names'

- name: Flush Handlers (Postgresql)
  meta: flush_handlers

- name: Configure primary for High Availability
  include_tasks: configure_standalone.yml
  when:
    - postgresql_ha_mode == True
    - mode == "non-containerized"
    - "'postgresql-primary' in group_names"

- name: Configure secondary for High Availability
  include_tasks: configure_standby.yml
  when:
    - postgresql_ha_mode == True
    - mode == "non-containerized"
    - "'postgresql-standby' in group_names"
