---

- name: Install Containerized PostgreSQL
  include_tasks: install_containerized.yml
  when: mode == "containerized"

- name: Flush Handlers (Postgresql)
  meta: flush_handlers

- name: Configure primary for High Availability
  include_tasks: configure_standalone.yml

- name: Configure primary for High Availability
  include_tasks: configure_standby.yml
