---

- name: "Apply workaround fix for Route53 TXT records"
  set_fact:
    record_value: "{{ (item.type == 'TXT') | ternary('\"' + item.value + '\"', item.value) }}"
  when:
    - item.value is defined 

- route53:
    zone: "{{ dns.1.dns_domain }}"
    record: "{{ item.record }}"
    value: '{{ record_value | default(omit) }}'
    type: "{{ item.type }}"
    ttl: "{{ item.ttl | default(omit) }}"
    state: "{{ item.state | default('present') }}"
