---

- name: 'Update Red Hat SSO management interface IP address'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/interface=management:write-attribute(name=inet-address,value="${jboss.bind.address.management:0.0.0.0}")'
  args:
    executable: "/bin/bash"

- name: 'Update Red Hat SSO private interface IP address'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/interface=management:write-attribute(name=inet-address,value="${jboss.bind.address.private:0.0.0.0}")'
  args:
    executable: "/bin/bash"

- name: 'Update Red hat SSO public interface IP address'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/interface=public:write-attribute(name=inet-address,value="${jboss.bind.address:0.0.0.0}")'
  args:
    executable: "/bin/bash"

- name: 'Add PostgreSQL JDBC Driver'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql,driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)'
  args:
    executable: "/bin/bash"

- name: 'Edit KeycloakDS datasource -- Add PostgreSQL database parameters'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=connection-url,value=jdbc:postgresql://{{ rh_sso_psql_db_url }}:{{ rh_sso_psql_db_port }}/keycloak)'
  args:
    executable: "/bin/bash"

- name: 'Edit KeycloakDS datasource -- Point KeycloakDS to use PostgreSQL JDBC driver'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=driver-name,value=postgresql)'
  args:
    executable: "/bin/bash"

- name: 'Edit KeycloakDS datasource -- Add keycloak database username'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=user-name,value={{ rh_sso_psql_db_user }})'
  args:
    executable: "/bin/bash"

- name: 'Edit KeycloakDS datasource -- Add keycloak database password'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=password,value={{ rh_sso_psql_db_pass }})'
  args:
    executable: "/bin/bash"

- name: 'Create PostgreSQL JDBC driver module definition'
  shell: >
    "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/jboss-cli.sh" -c
    --command='module add --name=system.layers.keycloak.org.postgresql --resources=/tmp/postgresql-42.2.16.jar --dependencies=javax.api,javax.transaction.api'
  args:
    executable: "/bin/bash"
